package com.example.todo.ui.design.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_outline = Color(0x33000000)
val md_theme_light_overlay= Color(0x0F000000)
val md_theme_light_onPrimary = Color(0xFF000000)
val md_theme_light_onSecondary = Color(0x99000000)
val md_theme_light_onTertiary = Color(0x4D000000)
val md_theme_light_onDisable = Color(0x26000000)
val md_theme_light_surface = Color(0xFFFFFFFF)
val md_theme_light_background = Color(0xFFF7F6F2)
val md_theme_light_red = Color(0xFFFF3B30)
val md_theme_light_green = Color(0xFF34C759)
val md_theme_light_blue = Color(0xFF007AFF)
val md_theme_light_gray = Color(0xFF8E8E93)
val md_theme_light_gray_light = Color(0xFFD1D1D6)
val md_theme_light_white = Color(0xFFFFFFFF)
val md_theme_light_pink = Color(0xFFFFE0DE)

val md_theme_dark_outline = Color(0x33FFFFFF)
val md_theme_dark_overlay= Color(0x52000000)
val md_theme_dark_onPrimary = Color(0xFFFFFFFF)
val md_theme_dark_onSecondary = Color(0x99FFFFFF)
val md_theme_dark_onTertiary = Color(0x66FFFFFF)
val md_theme_dark_onDisable = Color(0x26FFFFFF)
val md_theme_dark_surface = Color(0xFF252528)
val md_theme_dark_background = Color(0xFF161618)
val md_theme_dark_red = Color(0xFFFF453A)
val md_theme_dark_green = Color(0xFF32D74B)
val md_theme_dark_blue = Color(0xFF0A84FF)
val md_theme_dark_gray = Color(0xFF8E8E93)
val md_theme_dark_gray_light = Color(0xFF48484A)
val md_theme_dark_white = Color(0xFFFFFFFF)
val md_theme_dark_pink = Color(0xFF482A2B)
